spring :
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/myboard
    username : sa
    password : 1806

  jpa :
    hibernate:
      ddl-auto : create
    properties :
      hibernate :
        format_sql : true

logging.level:
  org.hibernate.SQL : debug

